sudo: false
language: node_js
node_js: stable
install: echo "Installation happens in the setup script"
cache: npm
notifications:
  email: false
branches:
  only:
    - master
script:
  - npm run setup
  - npx codecov
