name: Validate
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.13, 12, 14]
    steps:
      - uses: kentcdodds/kcd-workshop-validation-action@v1

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node: [10.13, 12, 14]
    steps:
      - uses: kentcdodds/kcd-workshop-validation-action@v1

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [10.13, 12, 14]
    steps:
      - uses: kentcdodds/kcd-workshop-validation-action@v1
